"
Instruments and graphical elemnts for performance in Gdansk at ESUG 2025
"
Class {
	#name : 'ManifestCodeInTheCorridor',
	#superclass : 'PackageManifest',
	#category : 'CodeInTheCorridor-Manifest',
	#package : 'CodeInTheCorridor',
	#tag : 'Manifest'
}

{ #category : 'code-critics' }
ManifestCodeInTheCorridor class >> ruleUnoptimizedToDoRuleV1FalsePositive [

	<ignoreForCoverage>
	^ #(#(#(#RGMethodDefinition #(#CorridorSpace #initializeHiHats #false)) #'2025-06-28T10:18:41.029966+02:00') )
]
